import Head from "next/head";
import { NextPage } from "next/types";
import { useState } from "react";
import LeaderboardTable from "../components/LeaderboardTable";

const Leaderboard: NextPage = () => {
  const [search, setSearch] = useState("");

  return (
    <>
      <Head>
        <title>Leaderboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center h-full w-full">
        <h1 className="text-emerald-700 text-2xl font-bold">
          Best Pastry Leaderboard
        </h1>
        <div className="w-4/12 py-4 flex justify-center items-center">
          <label htmlFor="">Search: </label>
          <div className="px-1"></div>
          <input
            onChange={(e) => setSearch(e.target.value)}
            className="rounded-sm px-1.5 py-0.5 min-w-[14rem] max-w-[16rem] w-10/12"
            type="text"
          />
        </div>
        <LeaderboardTable searchTerm={search} />
      </div>
    </>
  );
};

export default Leaderboard;
